name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change of cult.datastructure
        id: publish_nuget_cult_datastructure
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Cult.DataStructure/Cult.DataStructure.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${secrets.NUGET_API_KEY}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
