name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget_cult_configuration
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Cult.Configuration/Cult.Configuration.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
      - name: publish on version change
        id: publish_nuget_cult_cryptography
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Cult.Cryptography/Cult.Cryptography.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
